#!/usr/bin/php
<?php

declare(strict_types = 1);

/**
 * ClassMapBuilder
 */
class ClassMapBuilder {

    const PROLOGUE = "%s

/**
 *   ___ _     ___ _  _ ___ _    _          __ ___
 *  / __(_)_ _| _ \ || | _ \ |_ (_)_ _____ /  \_  )
 *  \__ \ \ \ /  _/ __ |  _/ ' \| \ V / -_) () / /
 *  |___/_/_\_\_| |_||_|_| |_||_|_|\_/\___|\__/___|
 *
 *   - The world\'s least sensible 6502 emulator -
 */

declare(strict_types=1);

namespace %s;
use \\RuntimeException;
use function \\spl_autoload_register;

if (PHP_VERSION_ID < 70400) {
    throw new RuntimeException('Requires at least PHP 7.4');
}

const CLASS_MAP = ";

    const EPILOGUE = ";

spl_autoload_register(function(string \$str_class): void {
    if (isset(CLASS_MAP[\$str_class])) {
        require_once __DIR__ . CLASS_MAP[\$str_class];
    }
});
";
    const EXCLUDE_PATTERNS = [
        '.'  => 1,
        '..' => 1
    ];

    const EXCLUDE_DIRS = [
        'src/tests' => 1
    ];

    /** @var string[] $aFiles */
    private array $aFiles = [];

    /** @var string[] $aClassMap */
    private array $aClassMap = [];

    /**
     * Main entry point
     *
     * @param string $sSourceDir
     * @param string $sNameSpace
     * @param bool   $bCheckNSOptimisation
     */
    public function execute(string $sSourceDir, string $sNameSpace, bool $bCheckNSOptimisation): void {
        $this->aFiles = [];
        $this->traverse($sSourceDir);
        $this->aClassMap = [];
        echo "Updating bootstrap...\n";
        foreach ($this->aFiles as $sSourcePath) {
            $this->processFile($sSourcePath);
        }
        $sCode = sprintf(self::PROLOGUE, "<?php", $sNameSpace) .
            str_replace(['array (', ')'], ['[', ']'], var_export($this->aClassMap, true)) .
            self::EPILOGUE;

        file_put_contents('src/bootstrap.php', $sCode);

        if ($bCheckNSOptimisation) {
            echo "Testing for global functions accessed within namespace...\n";
            foreach ($this->aFiles as $sFile) {
                $sTest = shell_exec('php -dvld.active=1 -dvld.execute=0 ' . $sFile . ' 2>&1 | grep INIT_NS');
                if (!empty($sTest)) {
                    echo $sFile, ":\n", $sTest, "\n";
                }
            }
        }
    }

    /**
     * Recurse over the directory structure
     *
     * @param string $sDirectory
     */
    private function traverse(string $sDirectory) {
        $oCurrentDir = dir($sDirectory);
        $sDirectory  = rtrim($sDirectory, '/');
        $aSubdirs    = [];

        while (false !== ($sItem = $oCurrentDir->read())) {


            if (isset(self::EXCLUDE_PATTERNS[$sItem])) {
                continue;
            }
            $sPath = $sDirectory . '/' . $sItem;
            if (isset(self::EXCLUDE_DIRS[$sPath]) || is_link($sPath)) {
                continue;
            }
            if (is_dir($sPath)) {
                $aSubdirs[] = $sPath;
            } else {
                if ('.php' === substr($sPath, -4, 4)) {
                    $this->aFiles[] = $sPath;
                }
            }
        }
        foreach ($aSubdirs as $sSubdir) {
            $this->traverse($sSubdir);
        }
    }



    /**
     * Extract namespace, interface, class and trait definitions from a source file
     *
     * @param string $sFile
     */
    private function processFile(string $sFile) {
        $sContent = file_get_contents($sFile);
        preg_match('/^namespace\s+([a-z0-9_\\\]+)/im', $sContent, $aMatches);
        $sNamespace = $aMatches[1] . '\\';
        preg_match_all('/^(class|interface|trait|abstract\s+class|final\s+class)\s+([a-z0-9_]+)/im', $sContent, $aMatches);
        $aMatches = $aMatches[2];
        $sFile    = substr($sFile, 3);
        foreach ($aMatches as $sName) {
            $this->aClassMap[$sNamespace . $sName] = $sFile;
        }
    }
}

$bCheckNSOptimisation = isset($_SERVER['argv'][1]);

(new ClassMapBuilder)->execute('src/', 'ABadCafe\SixPHPhive02', $bCheckNSOptimisation);
